[project]
name = "mcp-bootcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.88.0",
    "pip-system-certs>=5.2",
]
