[project]
name = "mcp-bootcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.3",
    "gunicorn>=23.0.0",
    "mcp[cli]>=1.9.4",
    "openai>=1.88.0",
    "pip-system-certs>=5.2",
]
